export type EnvVars = {
  SAUCE_DEMO_BASEURL: string;

  SAUCE_DEMO_PASSWORD: string;
  SAUCE_DEMO_INCORRECT_PASSWORD: string;

  SAUCE_DEMO_STANDARD_USER: string;
  SAUCE_DEMO_INCORRECT_USER: string;
  SAUCE_DEMO_LOCKED_OUT_USER: string;
  SAUCE_DEMO_PROBLEM_USER: string;
  SAUCE_DEMO_PERFORMACE_GLITCH_USER: string;
  SAUCE_DEMO_ERROR_USER: string;
  SAUCE_DEMO_VISUAL_USER: string;
};
